import './globals.css'

const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function App({ Component, pageProps }) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body>
        <Component {...pageProps} />
      </body>
    </html>
  )
}
